# Generated by Django 5.1.6 on 2025-03-28 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pecivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50)),
                ('popis', models.CharField(max_length=3000)),
                ('cena', models.FloatField(blank=True, null=True)),
                ('kategorie', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kategorie')),
            ],
        ),
    ]
