# Generated by Django 5.1.7 on 2025-03-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pecivo',
            old_name='name',
            new_name='jmeno',
        ),
        migrations.RenameField(
            model_name='pecivo',
            old_name='description',
            new_name='popis',
        ),
    ]
