# Generated by Django 5.1.7 on 2025-04-03 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50)),
                ('recept', models.CharField(max_length=1000)),
                ('kategorie', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kategorie')),
            ],
        ),
    ]
