# Generated by Django 5.1.7 on 2025-04-03 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_recept'),
    ]

    operations = [
        migrations.CreateModel(
            name='PecivoKategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorie', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.kategorie')),
                ('pecivo', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.pecivo')),
            ],
        ),
    ]
