# Generated by Django 5.1.6 on 2025-05-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pecivokategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategorie',
            name='cislo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
