# Generated by Django 5.1.6 on 2025-05-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_kategorie_cislo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategorie',
            name='cislo',
        ),
        migrations.AddField(
            model_name='kategorie',
            name='cislo_kategorie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kategorie',
            name='jmeno',
            field=models.CharField(max_length=100),
        ),
    ]
