# Generated by Django 5.1.6 on 2025-05-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_kategorie_cislo_kategorie_cislo_kategorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obrazek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrazek_url', models.URLField(max_length=500)),
            ],
        ),
    ]
