# Generated by Django 5.1.7 on 2025-05-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_pecivo_obrazek_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pecivo',
            name='cena',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
